import { MotorbikeListing } from '@/types/motorbike'

export const MOCK_MOTORBIKE: MotorbikeListing = {
  id: 'demo',
  created_at: new Date().toISOString(),
  title: 'Honda Air Blade 125 — Automatic Scooter',
  brand: 'Honda',
  model: 'Air Blade 125',
  type: 'scooter',
  engine_cc: 125,
  year_made: 2023,
  condition: 'like-new',
  color: 'Pearl White',
  district: 'an-thuong',
  district_label: 'An Thuong',
  price_per_day_usd: 7,
  price_per_week_usd: 40,
  price_per_month_usd: 120,
  deposit_usd: 50,
  helmet_included: true,
  lock_included: true,
  raincoat_included: false,
  insurance_included: true,
  delivery_available: true,
  delivery_fee_usd: null,
  gps_tracker: false,
  phone_holder: true,
  usb_charger: true,
  top_box: false,
  min_rental_days: 1,
  available_date: null,
  notes: '2023 model, still under warranty. Free delivery within 5km of An Thuong / My Khe area.',
  images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80'],
  video_url: null,
  cover_image_index: 0,
  status: 'available',
  featured: true,
  view_count: 0,
  inquiry_count: 0,
}
